version: '3.7'

services:
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      # - FLASK_APP=project/__init__.py
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:${DBPASSWORD}@www.iforest.net:5432/users_prod # new
      - DATABASE_TEST_URL=postgres://postgres:${DBPASSWORD}@www.iforest.net:5432/users_test # new
    # depends_on: # new
    #   - users-db

  # users-db: # new
  #   build:
  #     context: ./services/users/project/db
  #     dockerfile: Dockerfile
  #   expose:
  #     - 5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client

  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - REACT_APP_USERS_SERVICE_URL=http://13.59.123.253
    ports:
      - '3007:80'
    depends_on:
      - users
