"""empty message

Revision ID: 827d9bd9c1a2
Revises: 166562d2d237
Create Date: 2020-08-18 13:14:54.120838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827d9bd9c1a2'
down_revision = '166562d2d237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
